language: php

sudo: false

env:
  global:
    - IS_HHVM=no

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: hhvm-3.13
      sudo: required
      dist: trusty
      group: edge
      env: IS_HHVM=yes
  allow_failures:
    - php: 7.1
    - php: hhvm-3.13
  fast_finish: true

services:
  - redis-server

before_install:
  - if [[ $IS_HHVM == "yes" ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi

install: travis_retry composer install --no-interaction --prefer-source --no-suggest

script: vendor/bin/phpunit