sudo: false

language: php

php:
  - 7.0
  - 7.1
  - hhvm

services:
  - redis-server

install: travis_retry composer install --no-interaction --prefer-source --dev

script: vendor/bin/phpunit

matrix:
  allow_failures:
    - php: hhvm