language: php

sudo: false

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: hhvm-3.12
      sudo: required
      dist: trusty
      group: edge
  allow_failures:
    - php: 7.1
    - php: hhvm-3.12
  fast_finish: true

services:
  - redis-server

install: travis_retry composer install --no-interaction --prefer-source --dev

script: vendor/bin/phpunit